### ISSUE TITLE
Unexpected token export with with current version 1.6.1

### ISSUE THREAD

**Issue by achimbode** [mattias-persson/url-parameters#2]
Hi Mattias,
This lib looks very promising!
Unfortunately I get this error with the current version 1.6.1 in a react project - any idea where it comes from?
Might have to do with SSR...

```
｢hot｣: webpack: Compiling Done
/Users/achim/projects/hifi-studio-client/node_modules/url-parameters/index.js:168
export default new Url();
^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at eval (webpack-internal:///url-parameters:1:18)
```
Thanks in advance and all the best,
Achim

**Comment by mattias-sanfridsson** [comment]
Hi @achimbode ! Thanks for your report.

Would you mind sharing your setup so that I try to reproduce the issue?

**Comment by mattias-sanfridsson** [comment]
Closing due to inactivity.
